### ISSUE TITLE
win764位 java版本 11.01 客户端无法运行

### ISSUE THREAD

**Issue by InvisibleLeVen** [rebeyond/Behinder#10]

**Comment by InvisibleLeVen** [comment]
![image](https://user-images.githubusercontent.com/24772156/47251856-cf0b9780-d46c-11e8-91c1-a4564e60eec2.png)

**Comment by InvisibleLeVen** [comment]
动态加密和字节码解释执行这样确实能绕过现在大部分waf，但是如果waf hook了解释执行的函数，那么这种方法也无效了。

**Comment by rebeyond** [comment]
换java9之前的版本试一下。

冰蝎是绕过基于流量的waf。本地hook，这种类似RASP的检测，是另外一个话题了。

**Comment by InvisibleLeVen** [comment]
好的，谢谢
