### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by cuze** [rebeyond/Behinder#109]
系统: Windows 10 2004 专业版
Java:  java 11.0.8 2020-07-14 LTS  (64 bit)
报错:
![image](https://user-images.githubusercontent.com/41139915/95942204-33bc1b80-0e15-11eb-9083-15d04d7f90bf.png)

**Comment by burniceberg** [comment]
it’s same to me

**Comment by zxcyyyyy000** [comment]
it’s same to me

**Comment by chalan630** [comment]
it’s same to me

**Comment by awsl404** [comment]
it’s same to me

**Comment by rebeyond** [comment]
OK，后续版本会修复。
