### ISSUE TITLE
终端命令结果不能复制

### ISSUE THREAD

**Issue by ztl92493** [rebeyond/Behinder#11]
反馈两个问题 终端命令结果不能复制  命令执行的地方有时候执行程序会卡死  只能重新连接

**Comment by rebeyond** [comment]
“终端命令结果不能复制”，这个问题下个版本我修复一下。
“命令执行的地方有时候执行程序会卡死”，这个能不能提供一下具体的命令或者场景？

**Comment by rebeyond** [comment]
这个issue在v2.0版本已经修复。
