### ISSUE TITLE
文件管理 带中文的路径无法打开

### ISSUE THREAD

**Issue by ccz666** [rebeyond/Behinder#132]
版本是最新的v3.0 beta 6
就这样
![image](https://user-images.githubusercontent.com/40239133/109373585-a8868280-78ea-11eb-9988-d9c721c6c6ac.png)

**Comment by rebeyond** [comment]
> 版本是最新的v3.0 beta 6
> 就这样
> ![image](https://user-images.githubusercontent.com/40239133/109373585-a8868280-78ea-11eb-9988-d9c721c6c6ac.png)

服务器是什么版本的系统？web容器是什么？

**Comment by ccz666** [comment]
> > 版本是最新的v3.0 beta 6
> > 就这样
> > ![image](https://user-images.githubusercontent.com/40239133/109373585-a8868280-78ea-11eb-9988-d9c721c6c6ac.png)
> 
> 服务器是什么版本的系统？web容器是什么？


抱歉哈，也没想过会回我
web容器是iis，试了好3个同样的shell都不行
用菜刀是可以的，改成了UTF-8编码
这边用的官网下的最新64位java
windows10

**Comment by zjacai** [comment]
Windows NT 6.3.9600.0  IIS NET 版本:4.0.30319.42000，文件管理功能  中文目录打不开

**Comment by rebeyond** [comment]
fixed.

**Comment by ohyessir** [comment]
> Windows NT 6.3.9600.0 IIS NET 版本:4.0.30319.42000，文件管理功能 中文目录打不开
> 
> 建议能不能像菜刀一样，加个编码设置

你好，最后是怎么解决的？作者让我看你这个问题。
