### ISSUE TITLE
new shell.jsp returns 404 problem

### ISSUE THREAD

**Issue by git801** [rebeyond/Behinder#133]
i use behinder connect ot a shell.jsp,when i upload a new cmd.jsp or use function new file to create a cmd.jsp at the same path.I can see the cmd.jsp in file manager and command-line,but i can not connect or visit it,it returns 404,that`s why? I can not understand,would you like to give me a hand,thank you so much.

**Comment by rebeyond** [comment]
这个大概率和你新建的文件内容有关系，新建的文件被防护系统识别到了，可以创建个无害的jsp文件试一下。

**Comment by git801** [comment]
> 这个大概率和你新建的文件内容有关系，新建的文件被防护系统识别到了，可以创建个无害的jsp文件试一下。

thank you very much.god bless you
