### ISSUE TITLE
数据库错误 the database file is locked 

### ISSUE THREAD

**Issue by hongwei520** [rebeyond/Behinder#134]
![image](https://user-images.githubusercontent.com/39451921/109414932-c807d300-79f0-11eb-8ace-f0a9a97038d5.png)

**Comment by rebeyond** [comment]
下个版本会修复这个问题。

**Comment by hongwei520** [comment]
另外老哥 你这虚拟终端的功能是怎么实现 单纯的php代码能实现马




"&gt;<img&nbsp;src=x&gt;
1264766236@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rebeyond/Behinder"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月1日(星期一) 中午1:50
收件人:&nbsp;"rebeyond/Behinder"<Behinder@noreply.github.com&gt;;
抄送:&nbsp;""&gt;<img src=x onerror=alert`1`&gt;"<1264766236@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rebeyond/Behinder] 数据库错误 the database file is locked  (#134)





 
下个版本会修复这个问题。

**Comment by rebeyond** [comment]
新版本已修复。
