### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by Baikeryoyo** [rebeyond/Behinder#146]
Java版本为15
看到#115中有个大佬的办法
下载javafx-sdk-11.0.2，解压缩
命令执行如下：
java --module-path "C:\Program Files\Java\javafx-sdk-11.0.2\bin" --add-modules=javafx.controls --add-modules=javafx.fxml --add-modules=javafx.base --add-modules=javafx.graphics --add-modules=javafx.web -jar Behinder.jar
报错提示如下：
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.web not found

**Comment by rebeyond** [comment]
不是"C:\Program Files\Java\javafx-sdk-11.0.2\bin"，是"C:\Program Files\Java\javafx-sdk-11.0.2\lib"。

**Comment by Baikeryoyo** [comment]
![image](https://user-images.githubusercontent.com/57838797/114296156-1a7cea80-9a99-11eb-9253-1f8f715576ef.png)
卡住了没反应
