### ISSUE TITLE
虚拟终端用不了？

### ISSUE THREAD

**Issue by fffzzl** [rebeyond/Behinder#147]
试过win10 wamp (没有禁函数)php7.4版本 命令执行-操作失败 Null input buffer 虚拟终端-cmd.exe 有内容就是指针是红色的不能输入
![image](https://user-images.githubusercontent.com/67791411/114304568-7e89c800-9b06-11eb-825f-dd8cacc04376.png)

![image](https://user-images.githubusercontent.com/67791411/114304544-539f7400-9b06-11eb-9fdd-762ad3989dd3.png)

然后ubuntu php8.0 （宝塔安装 解除exec system函数）命令执行可以使用 虚拟终端启动-没有内容 指针红色不能输入
![image](https://user-images.githubusercontent.com/67791411/114304580-88abc680-9b06-11eb-8249-1f72695bc168.png)
这是服务端问题还是客户端问题？

**Comment by rebeyond** [comment]
bug已在v3.0 beta8中修复。
