### ISSUE TITLE
beta8版本 php马连接报错

### ISSUE THREAD

**Issue by waterrr** [rebeyond/Behinder#152]
beta7正常
beta8异常
[ERROR]连接失败：java.lang.Exception:页面存在，但是无法获取密钥！
![3LltoEZXCrKWI2J](https://user-images.githubusercontent.com/15225499/114612652-fa396f80-9cd4-11eb-9182-97a46f40a53f.png)

**Comment by leezp** [comment]
beta8 怎么没了

**Comment by rebeyond** [comment]
用的什么web容器？

**Comment by MountCloud** [comment]
是哦，8重么没了

**Comment by Anonymous-ghost** [comment]
这种我在实战的碰到过。jsp也是这总存在用6连接没问题。7就报上面的错误

**Comment by rebeyond** [comment]
用beta9试试看。

**Comment by MountCloud** [comment]
wow

**Comment by waterrr** [comment]
> 用beta9试试看。

beta9 PHP5/7连接 BT/小皮/LNMP环境均测试正常！感谢大佬

**Comment by waterrr** [comment]
beta9 PHP5/7连接 BT/小皮/LNMP环境均测试正常！感谢大佬
