### ISSUE TITLE
文件管理中打开文件显示一片空白

### ISSUE THREAD

**Issue by A0620-00** [rebeyond/Behinder#161]
左下角显示“文件内容加载成功”，但没有内容，一片空白。菜刀显示是正常的。
另外希望像菜刀一样保存数据库连接配置，现在每次都要手动配置，不太方便。

**Comment by rebeyond** [comment]
下个版本准备加入配置保存功能。

**Comment by rebeyond** [comment]
v4.0已新增数据库连接配置保存功能。
