### ISSUE TITLE
javafx导致的运行问题

### ISSUE THREAD

**Issue by killdayu** [rebeyond/Behinder#169]
![微信截图_20210716103731](https://user-images.githubusercontent.com/62084769/125883208-07531bc6-e274-4b70-bca8-8de5e1d7a968.png)
下载javafx压缩包全部解压到冰蝎根目录即可。
ps：我记得之前有解压lib到根目录这个的提示，现在不知道为啥找不到了，我穿越了？？？

**Comment by rebeyond** [comment]
这个提示在v4.0已经取消了。
