### ISSUE TITLE
mac端存在乱码

### ISSUE THREAD

**Issue by mbx119** [rebeyond/Behinder#171]
<img width="1192" alt="图片" src="https://user-images.githubusercontent.com/57660634/130164346-ab7b59ad-f979-4c53-b04d-69d539ac5c32.png">

**Comment by AidenSmith09** [comment]
不要使用 jdk11 使用Mac自带的java，或使用jdk16

**Comment by mbx119** [comment]
好的感谢

**Comment by frankli0324** [comment]
https://bugs.openjdk.java.net/browse/JDK-8234916
请使用新版openjfx
