### ISSUE TITLE
数据库连接问题

### ISSUE THREAD

**Issue by RedEyesD** [rebeyond/Behinder#182]
使用冰蝎的数据库连接工具的时候如果密码中存在!@#这些字符的话就无法连接，这个有没有办法改进一下，你们都没有遇到这个问题吗

**Comment by EMU-TIME** [comment]
上面说是要URL编码一下，确实也怪麻烦的，

**Comment by atomr00t** [comment]
url编码就可以了 ，我也测试了半天
