### ISSUE TITLE
MySql密码有@无法连接啊

### ISSUE THREAD

**Issue by LzwCracker** [rebeyond/Behinder#185]

**Comment by rebeyond** [comment]
您发给我的邮件已经收到，谢谢！-----------------------------邱永单位：江苏省南京医科大学公共卫生学院流行病与卫生统计学系电话：18994029188地址：江苏省南京市汉中路140号

**Comment by sevck** [comment]
+1 之前也遇到过
BTW：是不是不小心粘贴错了？

**Comment by rebeyond** [comment]
把@进行一下URL编码（%40）。
