### ISSUE TITLE
当web应用使用request response包装类时会导致链接失败

### ISSUE THREAD

**Issue by Y4er** [rebeyond/Behinder#187]
以springboot为例程序Filter中request和response被ContentCachingRequestWrapper、ContentCachingResponseWrapper包装 

<img width="934" alt="image" src="https://user-images.githubusercontent.com/40487319/160290796-c4fec963-042a-4f84-a645-62c219615ec0.png">

导致在链接时net.rebeyond.behinder.payload.java.Echo#fillContext setCharacterEncoding报错

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/40487319/160290878-2662a767-b504-4ab2-9b86-bb549d72c0b1.png">

并且org.springframework.web.util.ContentCachingResponseWrapper.ResponseServletOutputStream#ResponseServletOutputStream的write函数重载没有只传入一个byte[]参数的

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/40487319/160291306-8bd8c896-c89d-46a5-9d49-26be7006a35d.png">

所以这个地方也会报错，导致连不上。

<img width="810" alt="image" src="https://user-images.githubusercontent.com/40487319/160291349-e9ab08ad-9cc4-424f-8301-6eb75d7a457a.png">

鉴于dofilter的包装类被广泛应用，建议作者应修复此bug。

另外这是我对当前打内存马的一点建议，传入pagecontext时

<img width="947" alt="image" src="https://user-images.githubusercontent.com/40487319/160291518-91d72f9a-2b8e-49fa-903c-70ed71824933.png">

**Comment by rebeyond** [comment]
谢谢反馈，下个版本会考虑兼容Filter等Web组件。
