### ISSUE TITLE
连接excheng失败

### ISSUE THREAD

**Issue by Louisnie** [rebeyond/Behinder#192]
师傅，请问一下如何使用冰蝎连接exchenge服务器？一直显示失败，这个文章看的也不是很懂https://3gstudent.github.io/%E6%B8%97%E9%80%8F%E5%9F%BA%E7%A1%80-Exchange%E4%B8%80%E5%8F%A5%E8%AF%9D%E5%90%8E%E9%97%A8%E7%9A%84%E6%89%A9%E5%B1%95

**Comment by rebeyond** [comment]
您发给我的邮件已经收到，谢谢！-----------------------------邱永单位：江苏省南京医科大学公共卫生学院流行病与卫生统计学系电话：18994029188地址：江苏省南京市汉中路140号

**Comment by Louisnie** [comment]
> 师傅，请问一下如何使用冰蝎连接exchenge服务器？一直显示失败，这个文章看的也不是很懂https://3gstudent.github.io/%E6%B8%97%E9%80%8F%E5%9F%BA%E7%A1%80-Exchange%E4%B8%80%E5%8F%A5%E8%AF%9D%E5%90%8E%E9%97%A8%E7%9A%84%E6%89%A9%E5%B1%95

解决了
