### ISSUE TITLE
php马default_xor、default_aes协议无法连接

### ISSUE THREAD

**Issue by zR00t1** [rebeyond/Behinder#195]
客户端环境：java version "1.8.0_261"
服务端php版本：PHP/5.2.17、PHP/5.3.29、PHP/7.3.4
传输协议：default_xor、default_aes

![image](https://user-images.githubusercontent.com/46400438/180698488-ec268d63-66ce-4a3c-962f-44f329b9621e.png)

![image](https://user-images.githubusercontent.com/46400438/180697598-b1bd856d-0a2d-4755-8abf-6d20416fdd64.png)

![image](https://user-images.githubusercontent.com/46400438/180697723-80b3ca27-0f43-4cdf-9d75-efceb4749ea0.png)

![image](https://user-images.githubusercontent.com/46400438/180697893-7b3f4f13-31a0-4466-a9f6-aac46f814044.png)

**Comment by timetravel-boy** [comment]
我也是，连不上

**Comment by caonima-png** [comment]
同上连不上

**Comment by youyuzhongli** [comment]
同上连不上

**Comment by rebeyond** [comment]
内置传输协议存在逻辑错误，Behinder v4.0.1已修复该问题。
