### ISSUE TITLE
MacOS找不到 tools.jar

### ISSUE THREAD

**Issue by 14u9h** [rebeyond/Behinder#206]
报错问题：本地机器上没有找到编译环境，请确认:1是否安装了JDK环境;2./Library/Interne tPlug-Ins/JavaAppletPluginplugin/Contents/Home/lib目录下是否有toolsjar

我的解决过程：
查看当前安装的jdk路径 $ /usr/libexec/java_home -V | grep jdk
发现有两个，分别为：/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home;
/Library/Java/JavaVirtualMachines/jdk1.8.jdk/Contents/Home;

将/Library/Java/JavaVirtualMachines/jdk1.8.jdk/Contents/Home/lib中的tools.jar复制到/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib目录下解决问题
0.0

**Comment by xsshk** [comment]
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/71780423/182089376-a57eb1a0-b470-4819-9ad9-37a00189a334.png">
按照楼主的方式试着搞了下，但还是不行
MAC OS 13

**Comment by 14u9h** [comment]
> <img alt="图片" width="1114" src="https://user-images.githubusercontent.com/71780423/182089376-a57eb1a0-b470-4819-9ad9-37a00189a334.png">
> 
> 按照楼主的方式尝试下，但还是不能 MAC OS 13

遇事不决，重启试试，也可以试试添加环境变量到/Library/Java/

**Comment by 14u9h** [comment]
> <img alt="image" width="1114" src="https://user-images.githubusercontent.com/71780423/182089376-a57eb1a0-b470-4819-9ad9-37a00189a334.png">
> 
> 按照楼主的方式试着搞了下，但还是不行 MAC OS 13

遇事不决先重启，然后也可以尝试一下环境变量改到/Library/Java/这一串下。

**Comment by Laura0xiaoshizi** [comment]
用这个java环境启动就行了 /Library/Java/JavaVirtualMachines/jdk1.8.jdk/Contents/Home

**Comment by Rendevous-198** [comment]
谢谢 解决了。目前主机上有oracle1.8和zulu-1.8，尝试了下oracle1.8打不开，报缺少tools.jar。将zulu-1.8的tools.java（/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/lib/tools.jar） cp到oracle1.8（/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib）下可以了

**Comment by pbfochk** [comment]
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
