### ISSUE TITLE
jdk10+tomcat9注入agent内存马成功，但是连接404

### ISSUE THREAD

**Issue by liuhengliang666** [rebeyond/Behinder#219]
![image](https://user-images.githubusercontent.com/70633508/187138467-ce68a99a-26ac-4b9b-87f3-717fa7ec365c.png)
![image](https://user-images.githubusercontent.com/70633508/187138554-e4c2a60b-2b7f-421f-8243-1eaca0b61a02.png)

**Comment by liuhengliang666** [comment]
大佬，为啥不回复小弟呢

**Comment by rebeyond** [comment]
这个问题已经修复了，等下个版本更新。

**Comment by SummerSec** [comment]
+1

**Comment by rebeyond** [comment]
问题已在v4.0.6中修复。
