### ISSUE TITLE
MacOS测试连接shell异常，请问有师傅遇到过吗

### ISSUE THREAD

**Issue by xiaoxin-sec** [rebeyond/Behinder#222]
mac m1芯片
操作系统版本macos 12.5.1

java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)

使用127.0.0.1连接正常
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/41175075/188541599-48488611-fa8b-46e2-aa4e-cb675e323baf.png">

使用wifi网卡ip提示解密失败，响应码502
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/41175075/188541428-4eab830f-d826-4597-9e7d-ff6fce5f7208.png">

使用冰蝎3 11beta版本情况一样
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/41175075/188541997-d68b6f4e-a56f-49bd-8a5e-9188f5507da9.png">
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/41175075/188542129-39be5490-c656-4726-9f66-d65f18608bf8.png">

测试连接一些公网机器也同样连不上去
系统防火墙是关闭的

**Comment by xiaoxin-sec** [comment]
已解决

**Comment by tx1ee** [comment]
怎么解决的

**Comment by sh1nchan-sec** [comment]
> 怎么解决的

换了jdk解决的
