### ISSUE TITLE
Mac下连接木马为啥404，windows正常

### ISSUE THREAD

**Issue by zzqsmile** [rebeyond/Behinder#225]
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/38462538/188850542-1480f672-54b4-4970-aac1-9b66cb595e8d.png">
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/38462538/188850605-b755ecbf-14ef-4347-91cf-401f90c3b206.png">
Mac下连接木马为啥404，windows正常，大佬求解决

**Comment by rebeyond** [comment]
应该是你web服务环境的问题，用浏览器访问确认一下。

**Comment by Hwwg** [comment]
师傅解决了，我也出现一样的问题

**Comment by 11listen** [comment]
可能是挂了clashX代理的问题，我退了就能连了，前面一直连不上，在虚拟机里面开windows是正常的，mac连接一直404，退了clashX代理就能连上了
