### ISSUE TITLE
MAC使用自动操作app启动Behinder启动失败

### ISSUE THREAD

**Issue by yzd6k** [rebeyond/Behinder#230]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/43082769/196325447-717a0594-bad6-48ec-89a1-d9ca833a0f0f.png">
这样运行点启动后，页面弹出一下就关闭了
在命令 输入`java -jar Behinder.jar`就能正常启动
有大佬知道怎么解决吗

**Comment by Look4your** [comment]
你的环境肯定有多个jdk，用jdk8启动就不会出去这个问题

**Comment by rebeyond** [comment]
新版本客户端已经兼容Java8~Java19。
