### ISSUE TITLE
既然需要远程加密，为啥shell中只含有解密函数？

### ISSUE THREAD

**Issue by beenjoke** [rebeyond/Behinder#253]
那怎么加密传输回来呢

**Comment by ViCrack** [comment]
作者有在首页上放分析文章

**Comment by 89BaJiu** [comment]
> 

我看了分析文章，好像没提这事，，

**Comment by 89BaJiu** [comment]
> 作者有在首页上放分析文章

我看了分析文章，好像没提到这事，，

**Comment by B1aK2** [comment]
以default_xor_base64加密的php马为例，每次请求传递的加密数据中会有对应的 Encrypt()解密函数。
可以给冰蝎挂上burp的代理自己看下数据包。

**Comment by mmrems** [comment]
每次请求包都会包含加密函数Encrypt()
