### ISSUE TITLE
Behinder.jar 4.0.6 运行失败

### ISSUE THREAD

**Issue by QiLin713** [rebeyond/Behinder#258]
$ java -version

openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7)
OpenJDK 64-Bit Server VM (build 19.0.2+7, mixed mode)

$ java -jar Behinder.jar

(java:5651): Gdk-CRITICAL **: 10:49:57.367: gdk_x11_display_set_window_scale: assertion 'GDK_IS_X11_DISPLAY (display)' failed
'#'
'#'A fatal error has been detected by the Java Runtime Environment:
'#'
'#'  SIGSEGV (0xb) at pc=0x00007f1a01ae9f4d, pid=5651, tid=5687
'#'
'#' JRE version: OpenJDK Runtime Environment (19.0.2+7) (build 19.0.2+7)
'#' Java VM: OpenJDK 64-Bit Server VM (19.0.2+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
'#' Problematic frame:
'#' C  [libX11.so.6+0x2cf4d]
'#'
'#'Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/user/tool/Behinder_v4.0.6/core.5651)
'#'
'#'An error report file with more information is saved as:
'#'/home/user/tool/Behinder_v4.0.6/hs_err_pid5651.log
'#'
'#'If you would like to submit a bug report, please visit:
'#'   https://bugreport.java.com/bugreport/crash.jsp
'#' The crash happened outside the Java Virtual Machine in native code.
'#'See problematic frame for where to report the bug.
'#'
zsh: IOT instruction (core dumped)  java -jar Behinder.jar

$ echo $DISPLAY

:1

**Comment by rebeyond** [comment]
fixed.
