### ISSUE TITLE
关于4.0.6版本报毒

### ISSUE THREAD

**Issue by GoSeemHam23** [rebeyond/Behinder#265]
请问我下载后chrome浏览器和卡巴斯基直接报毒并删除恶意文件，这是怎么回事啊？

**Comment by rebeyond** [comment]
您发给我的邮件已经收到，谢谢！-----------------------------邱永单位：江苏省南京医科大学公共卫生学院流行病与卫生统计学系电话：18994029188地址：江苏省南京市汉中路140号

**Comment by qn9301** [comment]
您好，我已收到您的来信，我会尽快给您回复。

**Comment by Hesper2004** [comment]
我的也有，是报错了嘛
