### ISSUE TITLE
上传完文件之后会占用本地文件

### ISSUE THREAD

**Issue by lovelyjuice** [rebeyond/Behinder#268]
明明已经上传完成了，但是java.exe还是会占用本地的文件，导致本地文件无法重命名，关掉shell界面都不行，必须把冰蝎主程序关掉才能操作文件。
![image](https://github.com/rebeyond/Behinder/assets/20644461/986b139b-586b-40eb-ba11-f0379f9bafe4)

**Comment by rebeyond** [comment]
fixed.
