### ISSUE TITLE
PHP下的BUG

### ISSUE THREAD

**Issue by AruiRT** [rebeyond/Behinder#270]
<img width="706" alt="微信截图_20230617141804" src="https://github.com/rebeyond/Behinder/assets/31634136/dae44ddb-04c3-41b0-a143-e9a326b3f6f5">
这个我自己修改后的，麻烦师傅有空解决一下php的其他兼容问题
<img width="751" alt="微信截图_20230617141924" src="https://github.com/rebeyond/Behinder/assets/31634136/6d3817c3-65dd-4af6-9dfd-ff22079774ec">

**Comment by rebeyond** [comment]
fuction()[num]-like style fixed.
