### ISSUE TITLE
Behinder_v4.1.t00ls 双击启动有问题

### ISSUE THREAD

**Issue by fppecy** [rebeyond/Behinder#280]
javaversion 1.8.0_361
Behinder_v3.0_Beta_11.t00ls双击启动正常
Behinder_v4.1.t00ls 双击jar启动报错
![image](https://github.com/rebeyond/Behinder/assets/44750501/520553dc-f25c-425d-a2ec-92cdfaad37cd)

**Comment by fppecy** [comment]
命令行
![image](https://github.com/rebeyond/Behinder/assets/44750501/14768d95-b62d-47a5-b147-51b43c3db511)

**Comment by Janhsu** [comment]
一样的情况

**Comment by ChengCh1ng** [comment]
+1

**Comment by fppecy** [comment]
后来同时安装了java11跟java17别的jar工具双击打不开了，但是这个可以了。。。看别的issues好像是javaFX的问题

**Comment by fppecy** [comment]
重新安装了java环境 1.8.381
注册表计算机\HKEY_CLASSES_ROOT\Applications\javaw.exe下没有选项按照网上添加了
![image](https://github.com/rebeyond/Behinder/assets/44750501/67a82a95-a8e7-4847-945c-1acf16dd0848)

命令行倒是可以打开，双击还是不行。。。

后来修改了注册表将jre-1.8改成了jdk-1.8 双击打开没问题了

注册表路径：计算机\HKEY_CLASSES_ROOT\jarfile\shell\open\command
![image](https://github.com/rebeyond/Behinder/assets/44750501/4fe088d1-a549-41af-9efa-e005de2b7df8)
