### ISSUE TITLE
4.1版本Mac无法正常打开

### ISSUE THREAD

**Issue by L1ech0** [rebeyond/Behinder#297]
4.1版本Mac无法正常打开
<img width="437" alt="image" src="https://github.com/rebeyond/Behinder/assets/110832755/410d5768-543d-4b8b-9341-53b62693c8ae">

**Comment by 2331892928** [comment]
如果你不是中国人看不懂中国字，建议翻译

**Comment by jimtje** [comment]
> 如果你不是中国人看不懂中国字，建议翻译

人家用中文问的问题啊。没有答案没人逼着你回答，真可笑。

@L1ech0 应该试试 oracle jdk 1.8, https://www.oracle.com/java/technologies/javase/javase8u211-later-archive-downloads.html. 安装了找一下系统上装哪儿了，直接用安装的java运行。我这儿被装在 /Library/Java/JavaVirtualMachines/jdk-1.8.jdk/Contents/Home/。应该jdk8u381都可以用，只要能找到装在哪儿就行。一般不需要那么老的版本，但可以用就行。

**Comment by gyarmy** [comment]
谢谢！我会尽快查看！！

**Comment by Tripse** [comment]
> 谢谢！我会尽快查看！！

宝子，这是 jenv set env，供你参考：
```bash
jenv add /Library/Java/JavaVirtualMachines/jdk-1.8.jdk/Contents/Home/
jenv global oracle64-1.8.0.411

**Comment by hitjackma** [comment]
2024.12.16 
Mac M芯片， 可以用 java 17.0.6.fx-zulu 启动；
下载地址：https://cdn.azul.com/zulu/bin/zulu17.54.21-ca-fx-jdk17.0.13-macosx_aarch64.dmg

用 SDKMAN 安装的话：
`sdk install java 17.0.6.fx-zulu`

**Comment by gyarmy** [comment]
谢谢！我会尽快查看！！

**Comment by qn9301** [comment]
您好，我已收到您的来信，我会尽快给您回复。
