### ISSUE TITLE
jsp盘符为小写导致路径错误

### ISSUE THREAD

**Issue by yzddmr6** [rebeyond/Behinder#35]
![image](https://user-images.githubusercontent.com/46088090/62001459-8c759a80-b123-11e9-8364-f8d3f0dfdf3b.png)

点击打开路径就会报错
![image](https://user-images.githubusercontent.com/46088090/62001470-aadb9600-b123-11e9-9526-20f766712928.png)

把小写d改为大写才行

希望以后的版本可以修复这个bug

**Comment by rebeyond** [comment]
新版本已修复这个问题：）

**Comment by shmilylty** [comment]
请问新版本在什么地方呢？ @rebeyond

**Comment by rebeyond** [comment]
> 请问新版本在什么地方呢？ @rebeyond

还在开发中
