### ISSUE TITLE
页面存在，但是无法获取密钥!

### ISSUE THREAD

**Issue by liuhanyu200** [rebeyond/Behinder#41]
php版本：5.4.45
冰蝎使用的版本为2.0.1
同样的用菜刀能连接，冰蝎不能连接

**Comment by liuhanyu200** [comment]
已解决，之前没注意，只能用自己带的shell，其他shell不行

**Comment by lyh-ship** [comment]
> php版本：5.4.45
> 冰蝎使用的版本为2.0.1
> 同样的用菜刀能连接，冰蝎不能连接

上传冰蝎自带 的shell后，用get请求获取密钥，然后用密钥加密的payload是什么，上传到哪
