### ISSUE TITLE
下载文件时要选择本地文件才能下载

### ISSUE THREAD

**Issue by theLSA** [rebeyond/Behinder#56]
连上shell，文件管理，下载文件，要先选定一个本地文件才能下载，希望能改成下载文件自动保存到本地目录（不需要选定一个空文件，不然每次下载都要先创建一个空文件......）
环境：kali 2019.4+jdk 8+jsp shell

**Comment by rebeyond** [comment]
新版本已优化这个问题。

**Comment by rebeyond** [comment]
下载是不需要创建空白文件的，直接选择本地保存路径就可以，文件名也不用输入。

**Comment by ffdPuppy** [comment]
> 下载是不需要创建空白文件的，直接选择本地保存路径就可以，文件名也不用输入。

我刚刚试了一下，mac的不可以，需要选择路径文件夹不能确定，只能选择文件然后点击open
