### ISSUE TITLE
大哥你这db文件里面咋有一堆shell可以连

### ISSUE THREAD

**Issue by D4rkSec** [rebeyond/Behinder#65]
![image](https://user-images.githubusercontent.com/26535344/90341403-0a0f8f80-e032-11ea-89df-7e8498b53444.png)
![image](https://user-images.githubusercontent.com/26535344/90341424-30cdc600-e032-11ea-8193-3e321efd1d15.png)

**Comment by rebeyond** [comment]
感谢提醒，测试用的vps，已经404了。
