### ISSUE TITLE
报错错误: 找不到或无法加载主类 net.rebeyond.behinder.ui.Main 原因: java.lang.NoClassDefFoundError: javafx/application/Application

### ISSUE THREAD

**Issue by sherlockmj** [rebeyond/Behinder#68]
错误: 找不到或无法加载主类 net.rebeyond.behinder.ui.Main
原因: java.lang.NoClassDefFoundError: javafx/application/Application
![image](https://user-images.githubusercontent.com/32857102/90347660-54a9ff80-e064-11ea-92cf-5351f521c402.png)

**Comment by awanawana** [comment]
同原因

**Comment by awanawana** [comment]
> 
> 
> 错误: 找不到或无法加载主类 net.rebeyond.behinder.ui.Main
> 原因: java.lang.NoClassDefFoundError: javafx/application/Application
> ![image](https://user-images.githubusercontent.com/32857102/90347660-54a9ff80-e064-11ea-92cf-5351f521c402.png)

你下个jre8就可以了
https://www.oracle.com/java/technologies/javase-jre8-downloads.html

**Comment by sherlockmj** [comment]
> > 错误: 找不到或无法加载主类 net.rebeyond.behinder.ui.Main
> > 原因: java.lang.NoClassDefFoundError: javafx/application/Application
> > ![image](https://user-images.githubusercontent.com/32857102/90347660-54a9ff80-e064-11ea-92cf-5351f521c402.png)
> 
> 你下个jre8就可以了
> https://www.oracle.com/java/technologies/javase-jre8-downloads.html

在kali试验，无果

**Comment by zazi0001** [comment]
win10用楼上办法解决了

**Comment by Magi2B0y** [comment]
缺少javafx

**Comment by rebeyond** [comment]
v4.0.6版本已经集成了Javafx。
