### ISSUE TITLE
json报错是什么鬼

### ISSUE THREAD

**Issue by Aaron0-wang** [rebeyond/Behinder#7]
![default](https://user-images.githubusercontent.com/38186870/46593357-f02fc800-cafd-11e8-9119-cde7dbd53d11.png)

**Comment by rebeyond** [comment]
php版本是什么？

**Comment by Aaron0-wang** [comment]
> php版本是什么？

测试环境：centos7+PHP 5.4.16+nginx 1.12.2
软件运行环境：kali2.0+4.18内核+Java 1.8.0_181

**Comment by rebeyond** [comment]
有没有开始openssl扩展？用新版本试一下吧。

**Comment by Hzllaga** [comment]
我也遇到这个问题了

PHP Version 5.1.6
OpenSSL support | enabled
OpenSSL Version | OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008

**Comment by rebeyond** [comment]
客户端用的哪个版本？

**Comment by Hzllaga** [comment]
最新版 1.2

**Comment by rebeyond** [comment]
该issue在v2.0版本已修复。

**Comment by Hzllaga** [comment]
A JSONObject text must begin with '{' at 0 [character 1 line 1]  
2.0还是一样

**Comment by ViCrack** [comment]
作者可以在程序集成log打印，凡是当解析json失败的时候 比如在BasicInfoUtils就输出发送的数据，接收后原始的json串，还有没Decrypt之前的数据，这样就能方便定位

**Comment by rebeyond** [comment]
试试https://github.com/rebeyond/Behinder/releases/download/Behinder_v2.0.1/Behinder_v2.0.1.zip

**Comment by Hzllaga** [comment]
还是一样 @@

**Comment by rebeyond** [comment]
> 还是一样 @@

你用的是v2.0.1版的server端么？server端有更新。

**Comment by Hzllaga** [comment]
对的 用了2.0.1版的server端也是一样

**Comment by rebeyond** [comment]
> 对的 用了2.0.1版的server端也是一样

抓包看一下导致报错的http响应内容？

**Comment by Hzllaga** [comment]
> 抓包看一下导致报错的http响应内容？

两个POST包都返回空内容 两个GET都有返回一个随机值
