### ISSUE TITLE
页面存在，但是无法获取密钥

### ISSUE THREAD

**Issue by tammypi** [rebeyond/Behinder#70]
![image](https://user-images.githubusercontent.com/4264858/90350749-a48ec380-e070-11ea-8b41-c8caab6af36a.png)

**Comment by rebeyond** [comment]
对应web容器语言和版本是什么？

**Comment by tammypi** [comment]
已经解决了，原来shell文件里的那一串字符是密码的md5再取前16位。之前没有领悟到这一点。
