### ISSUE TITLE
关于密钥

### ISSUE THREAD

**Issue by hahaSec** [rebeyond/Behinder#71]
md5("admin")[0:16]，这个密钥的加密方式是啥~~rebeyond MD5加密后是eb5d925ba3f549b1，和e45e329feb5d925b对应不起来鸭~

**Comment by rebeyond** [comment]
加密方式没有直接使用md5，是取32位md5的前16位，(admin,32) = 21232f297a57a5a743894a0e4a801fc3，即：21232f297a57a5a7。

**Comment by hahaSec** [comment]
懂了，我还以为那个是MD5 16位小写加密后控制反转了一次呢.....

**Comment by xx-zhang** [comment]
我开始也是这样弄得`echo 'rebeyond' | md5sum | awk '{print $1}'`。。我自己后来测试了下
```python3
import hashlib 
_stat = hashlib.md5('rebeyond'.encode(encoding='UTF-8')).hexdigest()[0:16] == 'e45e329feb5d925b'
print(_stat )
#  True
```
