### ISSUE TITLE
[ERROR]连接失败：页面存在，但是无法获取密钥

### ISSUE THREAD

**Issue by littleheary** [rebeyond/Behinder#74]
我用的是phpstudy2018。
密钥用的是
21232f297a57a5a7
pass
e45e329feb5d925b
rebeyond

这四个都试了，全部都提示这些。

**Comment by lazybamboo** [comment]
PHP7.0以上版本试试

**Comment by sherlockmj** [comment]
![image](https://user-images.githubusercontent.com/32857102/90358002-589b4900-e087-11ea-90f1-55aa5dd93d8f.png)
同问php7.34

**Comment by sherlockmj** [comment]
试试删除代理

**Comment by Redem6ti0n** [comment]
新版自带的php马好像没用，用以前的马可以连

**Comment by Redem6ti0n** [comment]
php用以前的马可以

**Comment by Redem6ti0n** [comment]
php用以前的马可以

**Comment by NoOne52** [comment]
> 我用的是phpstudy2018。
> 密钥用的是
> 21232f297a57a5a7
> pass
> e45e329feb5d925b
> rebeyond
> 
> 这四个都试了，全部都提示这些。

我也是这样的，想在解决了吗？

**Comment by rebeyond** [comment]
> 我用的是phpstudy2018。
> 密钥用的是
> 21232f297a57a5a7
> pass
> e45e329feb5d925b
> rebeyond
> 
> 这四个都试了，全部都提示这些。

PHP版本是什么？容器用的哪个？

**Comment by NoOne52** [comment]
> > 我用的是phpstudy2018。
> > 密钥用的是
> > 21232f297a57a5a7
> > pass
> > e45e329feb5d925b
> > rebeyond
> > 这四个都试了，全部都提示这些。
> 
> PHP版本是什么？容器用的哪个？

5.0+，7.0+都试了，容器win+PHP study2018，是因为连接密码错了吗

**Comment by Redem6ti0n** [comment]
> 
> 
> > > 我用的是phpstudy2018。
> > > 密钥用的是
> > > 21232f297a57a5a7
> > > pass
> > > e45e329feb5d925b
> > > rebeyond
> > > 这四个都试了，全部都提示这些。
> > 
> > 
> > PHP版本是什么？容器用的哪个？
> 
> 5.0+，7.0+都试了，容器win+PHP study2018，是因为连接密码错了吗

我连上了 key换成echo  substr(md5("rebeyond"),0,16);的结果，密码就是rebeyond

**Comment by littleheary** [comment]
我是win+phpstudy2018,php用的是5.0+和7.0+，结果是5.0+的连不上，会报错。7.0+的可以正常连接。

**Comment by rebeyond** [comment]
PHP连接失败问题已修复。

**Comment by 1145319204** [comment]
冰蝎 v3.0.9 jsp马连接失败 
![image](https://user-images.githubusercontent.com/38741539/115331285-3afb2200-a1c8-11eb-998c-54e129274f82.png)
环境是 ：WebLogic Server 版本: 12.1.3.0.0     jdk1.8.0_181
