### ISSUE TITLE
页面存在，但是无法获取密钥

### ISSUE THREAD

**Issue by gahack** [rebeyond/Behinder#78]
我用冰蝎以前的旧版本妥妥的，用3的两个版本都无法连接，密码我没改就是用的作者默认的密码。目标jdk1.7.X，不知道咋了，要咋才能打开

**Comment by CNTJUSCSwyz** [comment]
那个给定的密码不是admin的md5吧，自己生成一个试试

**Comment by liao10086** [comment]
我也遇到了同样的问题， web容器是Apache，终端用的是mac，密码默认密码rebeyond

**Comment by rebeyond** [comment]
已在Behinder v3.0 Beta 3版本修复。
