### ISSUE TITLE
新版修复shell前后存在额外字符时无法连接的问题了吗？

### ISSUE THREAD

**Issue by lovelyjuice** [rebeyond/Behinder#80]
之前用sqlmap写shell的时候发现sqlmap上传文件时，有些时候会在末尾添加几个不可见字符。导致冰蝎连接出错，不知道3.0有没有修复这个问题？

**Comment by BloodPupil** [comment]
应该是没有，多余字符会影响冰蝎的客户端解密，所以会出错

**Comment by lovelyjuice** [comment]
> 应该是没有，多余字符会影响冰蝎的客户端解密，所以会出错

可以学习antsword加入自定义或随机生成的分隔符

**Comment by lovelyjuice** [comment]
我觉得有这个功能的好处是能够把webshell隐藏在正常的文件中，更加隐蔽难以发现。

**Comment by rebeyond** [comment]
2.0.1版本具备这个能力，新版本下个beta支持。

**Comment by rebeyond** [comment]
Beta6版本已恢复该功能。
