### ISSUE TITLE
 关于User-Agent的建议

### ISSUE THREAD

**Issue by shmilylty** [rebeyond/Behinder#81]
[冰蝎的前世今生：3.0新版本下的一些防护思考](https://mp.weixin.qq.com/s/WYM3J3daMTFODr4BSkKzxg)

针对User-Agent特征建议采取以下一种方法：
1.使用或自写随机User-Agent生成库，优点：完全随机，缺点：成本较高。
2.使用更多最新User-Agent列表，优点：成本较低，缺点：时效性较低。

针对第2条，有一个在线的网站可以获取最新User-Agent：
https://developers.whatismybrowser.com/useragents/explore/software_name/
例如较新的chrome有关User-Agent：https://developers.whatismybrowser.com/useragents/explore/software_name/chrome/

**Comment by rebeyond** [comment]
Beta3版本实现这个特性，thanks。

**Comment by rebeyond** [comment]
Beta3版本已更新User-Agent列表。
