### ISSUE TITLE
3.0的一个可能的流量特征

### ISSUE THREAD

**Issue by jjf012** [rebeyond/Behinder#83]
如题，以php为例。首次连接，服务器分配cookie。
![image](https://user-images.githubusercontent.com/13266057/90482712-3b897780-e166-11ea-9461-4b318c158905.png)
然后接着cookie就变成这样
![image](https://user-images.githubusercontent.com/13266057/90482747-493efd00-e166-11ea-9918-d63e75402ffb.png)

**Comment by rebeyond** [comment]
该问题已修复。
