### ISSUE TITLE
升级到最新版本后软件打不开了。

### ISSUE THREAD

**Issue by Asura88** [rebeyond/Behinder#85]
![image](https://user-images.githubusercontent.com/25000885/90576616-4d642c80-e1f1-11ea-8275-6c3071cfd265.png)

![image](https://user-images.githubusercontent.com/25000885/90576639-581ec180-e1f1-11ea-9e92-e07211622e70.png)

**Comment by Asura88** [comment]
@rebeyond #

**Comment by Asura88** [comment]
![image](https://user-images.githubusercontent.com/25000885/90576937-19d5d200-e1f2-11ea-8479-d8574baa51ce.png)

**Comment by rebeyond** [comment]
你升级之前用的哪个版本？

**Comment by rebeyond** [comment]
重新下载一下试试。

**Comment by Asura88** [comment]
我现在是最新版本啊，你刚刚更新的新版本存在这个问题。

**Comment by rebeyond** [comment]
> 我现在是最新版本啊，你刚刚更新的新版本存在这个问题。

刚刚更新了，你重新下载试试。

**Comment by Asura88** [comment]
![image](https://user-images.githubusercontent.com/25000885/90577880-7b973b80-e1f4-11ea-926d-d723951eaa43.png)

感谢，解决了。
