### ISSUE TITLE
beta3版本连接失败，无法获取秘钥

### ISSUE THREAD

**Issue by TriompheL** [rebeyond/Behinder#87]
beta2版本连接成功了
![image](https://user-images.githubusercontent.com/27794837/90586360-9d4eed80-e209-11ea-91a6-42e7ddb234bb.png)
![image](https://user-images.githubusercontent.com/27794837/90586381-ab047300-e209-11ea-893b-14344047485a.png)
beta显示 无法获取秘钥

**Comment by hixss** [comment]
密钥hash开头不能为0，换一个非0开头的即可。

**Comment by TriompheL** [comment]
> 密钥hash开头不能为0，换一个非0开头的即可。

我用的原始密码 rebeyond啊

**Comment by secStudy** [comment]
从抓的包来看，感觉是v2.0的特征呀。
![image](https://user-images.githubusercontent.com/64324326/90589497-d5a5fa00-e210-11ea-88b1-ff8a5ce8d293.png)

**Comment by rebeyond** [comment]
> beta2版本连接成功了
> ![image](https://user-images.githubusercontent.com/27794837/90586360-9d4eed80-e209-11ea-91a6-42e7ddb234bb.png)
> ![image](https://user-images.githubusercontent.com/27794837/90586381-ab047300-e209-11ea-893b-14344047485a.png)
> beta显示 无法获取秘钥

环境信息是什么？Java版本，OS类型，Web容器版本。

**Comment by secStudy** [comment]
使用beta2版本可以连接成功，但是beta3却是不成功。抓包看了一下，却是V2.0的流量特征

**Comment by secStudy** [comment]
java 版本 "1.8.0_251"，
OS: CentOS Linux release 7.8.2003 (Core)  
WEB容器：Apache Tomcat/7.0.75

**Comment by hixss** [comment]
> 密钥hash开头不能为0，换一个非0开头的即可。

详细描述一下，早上遇到一个现象，密钥开头不能为0，否则也会出现密钥获取失败。
可以拿以下这个例子做测试，
![image](https://user-images.githubusercontent.com/17995374/90590807-05a2cc80-e214-11ea-8255-4b484b553dcf.png)

失败：01d7f40760960e7b
成功：1d7f40760960e7bd

**Comment by TriompheL** [comment]
java版本 1.8.0_211
OS：win10
WEB容器： Apache Tomcat 8.0.30

**Comment by TriompheL** [comment]
> 使用beta2版本可以连接成功，但是beta3却是不成功。抓包看了一下，却是V2.0的流量特征

和你流量特征相同。
![image](https://user-images.githubusercontent.com/27794837/90595205-de053180-e21e-11ea-8402-944816bcfe87.png)

**Comment by TriompheL** [comment]
测试php通过了
![image](https://user-images.githubusercontent.com/27794837/90596246-1f96dc00-e221-11ea-94af-3ecec34bf619.png)

**Comment by TriompheL** [comment]
php是可以连接成功的。
![image](https://user-images.githubusercontent.com/27794837/90596361-61c01d80-e221-11ea-8bb8-38b3865c8961.png)

**Comment by TriompheL** [comment]
php是可以连接成功的。
![image](https://user-images.githubusercontent.com/27794837/90596442-84523680-e221-11ea-826a-4117c9642f6e.png)

**Comment by BloodPupil** [comment]
> 使用beta2版本可以连接成功，但是beta3却是不成功。抓包看了一下，却是V2.0的流量特征
> 
> 和你流量特征相同。

这个特征实在前期秘钥验证过程失败后发起的正常秘钥协商过程引起的，其实冰蝎3版本也是有这个特征的

**Comment by TriompheL** [comment]
问题已经解决，关闭讨论
