### ISSUE TITLE
jdk版本不对，导致无法打开

### ISSUE THREAD

**Issue by HyWell** [rebeyond/Behinder#9]
操作环境：MacOs、java10.0 使用java -XstartOnFirstThread -jar Behinder.jar无法打开，报错信息如下：class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader
通过更改jdk版本，更改为1.8可成功打开。
建议在readme中说明该情况，或者提供高版本jdk可运行版本

**Comment by rebeyond** [comment]
JDK9的release notes中提到: "The application class loader is no longer an instance of java.net.URLClassLoader (an implementation detail that was never specified in previous releases). Code that assumes that ClassLoader.getSytemClassLoader() returns a URLClassLoader object will need to be updated. 

冰蝎的客户端GUI采用了SWT开发，需要根据不同的OS平台加载不同的SWT库，因此用到了动态添加jar至classpath的能力。目前来看，JDK9已经不再允许动态添加jar至系统的classloader。我在readme中注明一下。
